// ============================================================
// YouFundThat — Données de démonstration
// Miroir exact de sql/03_seed_examples.sql — utilisé quand
// config.js ne renseigne pas de projet Supabase.
// Les scores sont recalculés côté client avec la MÊME logique
// que la base (décote temporelle incluse) — mode démo vérifiable.
// ============================================================
window.YFT_DEMO = {
  companies: [
    { id: "demo-1", name: "Apple Inc.",     wikidata_qid: "Q312",     country: "US", data_quality: 5 },
    { id: "demo-2", name: "TotalEnergies",  wikidata_qid: "Q154347",  country: "FR", data_quality: 4 },
    { id: "demo-3", name: "Meta Platforms", wikidata_qid: "Q380",     country: "US", data_quality: 5 },
    { id: "demo-4", name: "Triodos Bank",   wikidata_qid: "Q1068740", country: "NL", data_quality: 3 },
    { id: "demo-5", name: "Tesla / SpaceX", wikidata_qid: "Q478214",  country: "US", data_quality: 4 },
    { id: "demo-6", name: "Amazon.be",      wikidata_qid: "Q3884",    country: "US", data_quality: 5 },
  ],
  facts: [
    { company_id: "demo-1", axis: "fiscal", fact_type: "negative", weight: 3, year: 2024,
      description: "Arrêt CJUE C-465/20 — avantages fiscaux illégaux Irlande (définitif)",
      source_url: "https://curia.europa.eu/juris/document/C-465-20" },
    { company_id: "demo-1", axis: "fiscal", fact_type: "negative", weight: 2, year: 2014,
      description: "ICIJ LuxLeaks — structure Luxembourg documentée",
      source_url: "https://offshoreleaks.icij.org/luxleaks/apple" },
    { company_id: "demo-1", axis: "fiscal", fact_type: "negative", weight: 2, year: 2016,
      description: "Taux effectif ~1% sur profits UE — décision CE 2016",
      source_url: "https://ec.europa.eu/competition/state_aid/apple-2016" },

    { company_id: "demo-2", axis: "lobbying", fact_type: "negative", weight: 2, year: 2024,
      description: "Dépenses lobbying UE 2,8M€/an (LobbyFacts 2024)",
      source_url: "https://lobbyfacts.eu/datacard/totalenergies" },
    { company_id: "demo-2", axis: "lobbying", fact_type: "negative", weight: 2, year: 2025,
      description: "Score InfluenceMap E (2025)",
      source_url: "https://lobbymap.org/company/TotalEnergies" },
    { company_id: "demo-2", axis: "lobbying", fact_type: "negative", weight: 1, year: 2023,
      description: "Enquête CEO revolving door Commission (Corporate Europe Obs.)",
      source_url: "https://corporateeurope.org/totalenergies-revolving-door" },

    { company_id: "demo-3", axis: "data", fact_type: "negative", weight: 3, year: 2023,
      description: "Amende RGPD 1,2Mrd€ DPC Irlande (2023, définitif)",
      source_url: "https://www.dataprotection.ie/meta-decision-2023" },
    { company_id: "demo-3", axis: "data", fact_type: "negative", weight: 3, year: 2020,
      description: "Transferts UE→US sans garanties — arrêt Schrems II (2020)",
      source_url: "https://curia.europa.eu/juris/document/C-311-18" },
    { company_id: "demo-3", axis: "data", fact_type: "negative", weight: 2, year: 2025,
      description: "Infrastructure principale hors UE (US data centers)",
      source_url: "https://www.facebook.com/privacy/policy" },

    { company_id: "demo-4", axis: "labor", fact_type: "positive", weight: 2, year: 2024,
      description: "Aucun financement armement/fossile/tabac — politique publiée",
      source_url: "https://www.triodos.com/minimum-standards" },
    { company_id: "demo-4", axis: "labor", fact_type: "positive", weight: 1, year: 2024,
      description: "Rapport annuel 100% des prêts publiés en ligne (2024)",
      source_url: "https://www.triodos.com/know-where-your-money-goes" },

    { company_id: "demo-5", axis: "democracy", fact_type: "negative", weight: 2, year: 2024,
      description: "America PAC — 270M$ pour Trump 2024 (FEC)",
      source_url: "https://www.fec.gov/data/committee/america-pac" },
    { company_id: "demo-5", axis: "democracy", fact_type: "negative", weight: 1, year: 2025,
      description: "Soutien public AfD/Vox/Reform UK (déclarations publiques)",
      source_url: "https://archive.org/musk-afd-statements" },
    { company_id: "demo-5", axis: "democracy", fact_type: "negative", weight: 2, year: 2022,
      description: "Rachat Twitter/X — licenciement 80% des modérateurs (The Verge)",
      source_url: "https://www.theverge.com/twitter-moderation-layoffs" },

    { company_id: "demo-6", axis: "fiscal", fact_type: "negative", weight: 3, year: 2017,
      description: "CJUE : 250M€ avantages fiscaux illégaux Luxembourg (2017, définitif)",
      source_url: "https://ec.europa.eu/competition/amazon-luxembourg-2017" },
    { company_id: "demo-6", axis: "fiscal", fact_type: "negative", weight: 2, year: 2017,
      description: "Taux effectif ~1% sur profits UE (décision CE 2017)",
      source_url: "https://ec.europa.eu/competition/amazon-tax-2017" },
    { company_id: "demo-6", axis: "lobbying", fact_type: "negative", weight: 2, year: 2024,
      description: "Dépenses lobbying UE 4,2M€/an (LobbyFacts 2024)",
      source_url: "https://lobbyfacts.eu/datacard/amazon" },
    { company_id: "demo-6", axis: "lobbying", fact_type: "negative", weight: 1, year: 2025,
      description: "Score InfluenceMap D (lobbymap.org 2025)",
      source_url: "https://lobbymap.org/company/Amazon" },
    { company_id: "demo-6", axis: "data", fact_type: "negative", weight: 2, year: 2025,
      description: "Infrastructure principale hors UE (US) — données citoyens européens",
      source_url: "https://aws.amazon.com/privacy" },
    { company_id: "demo-6", axis: "data", fact_type: "negative", weight: 1, year: 2024,
      description: "Enquête RGPD APD belge en cours (2024)",
      source_url: "https://www.autoriteprotectiondonnees.be/amazon-enquete-2024" },
    { company_id: "demo-6", axis: "labor", fact_type: "negative", weight: 1, year: 2023,
      description: "Rapport conditions entrepôts (Reuters 2023)",
      source_url: "https://www.reuters.com/amazon-warehouse-2023" },
    { company_id: "demo-6", axis: "democracy", fact_type: "negative", weight: 1, year: 2024,
      description: "Dons PAC mixtes US (FEC) — sans engagement anti-démocratique direct",
      source_url: "https://www.fec.gov/data/amazon-pac" },
  ],
};
